# Practicando las consultas: ClassicModels

## Instalacion del SQLite3

In [ ]:
import sqlite3

## Montar unidad y establecer ruta
En el menú del lado izquierdo, seleccionamos la carpeta, luego hacemos clic en la carpeta "drive" y seguimos los pasos correspondientes.

Posteriormente, buscamos nuestra carpeta y copiamos la ruta de la que contiene todos los archivos en los que estamos trabajando, e incluimos esa ruta como la variable DRIVE_PATH.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Importando pandas

In [ ]:
import pandas as pd

## Importando la base de datos

In [ ]:
con = sqlite3.connect("/content/drive/MyDrive/NDS/SQL/Jun24/classic.db")

1. Calcula el promedio de ventas (cantidad de productos por precio) para cada región (país) en 2004. Muestra el país y el promedio de ventas.
2. Lista los clientes que han realizado pedidos de productos de al menos dos categorías diferentes (productline).
3. Encuentra el proveedor que más productos proporciona para cada categoría de producto. Incluye la categoría, el nombre del proveedor y el número de productos proporcionados.
4. Calcula el promedio facturado por mes durante el 2003.
5.  Lista todos los clientes que no han realizado ningun pedido en 2005. Muestra el nombre del cliente y la fecha de su último pedido.
6. Lista a los clientes con más ventas (cantidad de productos por precio) en cada país.

In [ ]:
q="""
WITH aux AS (
SELECT count(productCode),productline,productVendor,
 RANK() OVER(PARTITION BY productline ORDER BY COUNT(productCode) desc) rnk
FROM products
GROUP BY productVendor,productline)
SELECT * FROM aux

"""
pd.read_sql(q,con)

    count(productCode)   productline              productVendor  rnk
0                    6  Classic Cars    Classic Metal Creations    1
1                    5  Classic Cars       Gearbox Collectibles    2
2                    4  Classic Cars        Second Gear Diecast    3
3                    4  Classic Cars  Welly Diecast Productions    3
4                    3  Classic Cars   Carousel DieCast Legends    5
..                 ...           ...                        ...  ...
60                   1  Vintage Cars       Gearbox Collectibles    8
61                   1  Vintage Cars   Highway 66 Mini Classics    8
62                   1  Vintage Cars        Second Gear Diecast    8
63                   1  Vintage Cars       Unimax Art Galleries    8
64                   1  Vintage Cars  Welly Diecast Productions    8

[65 rows x 4 columns]

In [ ]:
q="""
SELECT count(productCode),productline,productVendor
FROM products
GROUP BY productVendor,productline
ORDER BY count(productCode) DESC
"""
pd.read_sql(q,con)

    count(productCode)       productLine              productVendor
0                    6      Classic Cars    Classic Metal Creations
1                    5      Classic Cars       Gearbox Collectibles
2                    4      Vintage Cars              Exoto Designs
3                    4      Classic Cars        Second Gear Diecast
4                    4      Classic Cars  Welly Diecast Productions
..                 ...               ...                        ...
60                   1      Vintage Cars       Unimax Art Galleries
61                   1       Motorcycles  Welly Diecast Productions
62                   1             Ships  Welly Diecast Productions
63                   1  Trucks and Buses  Welly Diecast Productions
64                   1      Vintage Cars  Welly Diecast Productions

[65 rows x 3 columns]

In [ ]:
q="""
SELECT productCode,productline,productVendor
FROM products
"""
pd.read_sql(q,con)

    productCode   productLine              productVendor
0      S10_1678   Motorcycles            Min Lin Diecast
1      S10_1949  Classic Cars    Classic Metal Creations
2      S10_2016   Motorcycles   Highway 66 Mini Classics
3      S10_4698   Motorcycles          Red Start Diecast
4      S10_4757  Classic Cars    Motor City Art Classics
..          ...           ...                        ...
105   S700_3505         Ships   Carousel DieCast Legends
106   S700_3962         Ships  Welly Diecast Productions
107   S700_4002        Planes        Second Gear Diecast
108    S72_1253        Planes    Motor City Art Classics
109    S72_3212         Ships       Unimax Art Galleries

[110 rows x 3 columns]